name: Jenkins CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start_jenkins:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Jenkins
        run: docker-compose up -d --build

      - name: Wait for Jenkins to start
        run: |
          for i in {1..30}; do
            if docker -f logs myBsMarvin 2>&1 | grep -q "Jenkins is fully up and running"; then
              echo "✅ Jenkins is up!"
              exit 0
            fi
            echo "⏳ Waiting for Jenkins... ($i/30)"
            sleep 5
          done
          echo "❌ Jenkins did not start in time."
          exit 1

      - name: Check for errors in logs
        run: |
          if docker logs myBsMarvin 2>&1 | grep -iE "SEVERE|FATAL|ERROR"; then
            echo "❌ Found errors in Jenkins logs!"
            exit 1
          fi
          echo "✅ No critical errors found."

      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_MIRROR_KEY }}
