name: Jenkins CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start_jenkins:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Jenkins
        run: docker-compose up -d --build

      - name: Wait for Jenkins to start
        run: |
          timeout=300
          while ! docker logs myBsMarvin 2>&1 | grep -q "Jenkins is fully up and running"; do
            if [ $timeout -le 0 ]; then
              echo "Timed out waiting for Jenkins"
              exit 1
            fi
            echo "Waiting for Jenkins to start... ($timeout seconds remaining)"
            timeout=$((timeout-5))
            sleep 5
          done

      - name: Check for errors in logs
        run: |
          if docker logs myBsMarvin 2>&1 | grep -iE "SEVERE|FATAL|ERROR"; then
            echo "❌ Found errors in Jenkins logs!"
            exit 1
          fi
          echo "✅ No critical errors found."

      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.REPO_URL }}
          ssh_private_key: ${{ secrets.SSH_MIRROR_KEY }}
